image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
- port: 9001
- port: 15672
  visibility: public
- port: 10000
  visibility: public
  
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
tasks:
  - openMode: tab-after
    name: "Services"
    command: service nginx start &
             cd /workspace/pwa-deals && /usr/sbin/php-fpm7.4 --fpm-config php-fpm.conf & 
             sudo /etc/init.d/supervisor start
  - name: "Terminal/SSH Start here"
    command: chmod a+rwx pwa-installer.sh && ./pwa-installer.sh && echo "Setup completed.."